"use client";

import { ContentPackage, SeniorityTier } from "@/lib/types";
import { PersonaBadge, TierBadge } from "./PersonaCard";

const TIER_ORDER: SeniorityTier[] = ["emerging", "established", "veteran"];

export function ContentPreview({ pkg }: { pkg: ContentPackage }) {
  return (
    <div className="space-y-6">
      <div className="rounded-lg border border-stone-200 bg-white p-6 shadow-sm">
        <div className="flex flex-wrap items-center gap-2">
          <span className="rounded-full bg-stone-100 px-2 py-0.5 text-xs font-medium text-stone-600">
            Blog post
          </span>
          <span className="rounded-full bg-brand-50 px-2 py-0.5 text-xs font-medium text-brand-700">
            {pkg.blog.wordCount} words
          </span>
          <span className="rounded-full bg-stone-100 px-2 py-0.5 text-xs font-medium text-stone-600">
            Generated by {pkg.generatedBy}
          </span>
        </div>
        <h2 className="mt-3 text-xl font-bold text-stone-900">{pkg.blog.title}</h2>
        <div className="mt-3">
          <p className="text-xs font-medium uppercase tracking-wide text-stone-400">Outline</p>
          <ul className="mt-1.5 list-inside list-disc space-y-0.5 text-sm text-stone-700">
            {pkg.blog.outline.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </div>
        <details className="mt-4 cursor-pointer">
          <summary className="text-sm font-medium text-brand-700 hover:text-brand-900">
            Read full draft
          </summary>
          <div className="prose-blog mt-3 border-t border-stone-100 pt-3">
            {renderMarkdownLite(pkg.blog.body)}
          </div>
        </details>
      </div>

      <div>
        <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-stone-500">
          Newsletter variants per persona
        </h3>
        <div className="grid gap-4 md:grid-cols-3">
          {pkg.newsletters.map((nl) => (
            <div
              key={nl.personaId}
              className="rounded-lg border border-stone-200 bg-white p-4 shadow-sm"
            >
              <div className="flex items-center justify-between">
                <PersonaBadge personaId={nl.personaId} />
              </div>
              <div className="mt-3">
                <p className="text-xs font-medium uppercase tracking-wide text-stone-400">
                  Subject
                </p>
                <p className="mt-0.5 text-sm font-semibold text-stone-900">{nl.subject}</p>
              </div>
              <div className="mt-2">
                <p className="text-xs font-medium uppercase tracking-wide text-stone-400">
                  Preheader
                </p>
                <p className="mt-0.5 text-xs text-stone-600">{nl.preheader}</p>
              </div>
              <div className="mt-3 rounded-md bg-stone-50 p-3 text-xs text-stone-700 whitespace-pre-line">
                {nl.body}
              </div>

              {/* First line per seniority tier - the seniority feature in action */}
              {nl.firstLineByTier && (
                <div className="mt-3 rounded-md border border-indigo-100 bg-indigo-50/40 p-3">
                  <p className="text-[11px] font-medium uppercase tracking-wide text-indigo-700">
                    First line by seniority tier
                  </p>
                  <div className="mt-2 space-y-2">
                    {TIER_ORDER.map((tier) => (
                      <div key={tier} className="text-[11px]">
                        <div className="mb-0.5">
                          <TierBadge tier={tier} />
                        </div>
                        <p className="italic text-stone-700">
                          "{nl.firstLineByTier![tier]}"
                        </p>
                      </div>
                    ))}
                  </div>
                  <p className="mt-2 text-[10px] text-indigo-700">
                    Swapped into body[0] at send time based on each recipient's tier. Same inner content, three openings.
                  </p>
                </div>
              )}

              <div className="mt-3 flex items-center justify-between border-t border-stone-100 pt-3">
                <span className="text-xs text-stone-500">CTA</span>
                <span className="rounded-md bg-brand-600 px-2 py-1 text-xs font-medium text-white">
                  {nl.cta.label}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function renderMarkdownLite(text: string): JSX.Element {
  const blocks = text.split(/\n\n+/);
  return (
    <>
      {blocks.map((b, i) => {
        if (b.startsWith("## ")) {
          return <h2 key={i}>{b.replace(/^##\s*/, "")}</h2>;
        }
        return <p key={i}>{b}</p>;
      })}
    </>
  );
}
