import { runPipeline } from "../src/lib/pipeline";

async function main() {
  const topic = process.argv.slice(2).join(" ") || "AI in creative automation";
  console.log(`\n🚀 Running pipeline for topic: "${topic}"\n`);

  const start = Date.now();
  const { run, contentPackage } = await runPipeline(topic);
  const duration = ((Date.now() - start) / 1000).toFixed(1);

  console.log(`✓ Blog generated: "${contentPackage.blog.title}"`);
  console.log(`  ${contentPackage.blog.wordCount} words, ${contentPackage.blog.outline.length} sections`);
  console.log(`  Generated by: ${contentPackage.generatedBy}\n`);

  console.log(`✓ Newsletters generated for ${contentPackage.newsletters.length} personas:`);
  for (const nl of contentPackage.newsletters) {
    console.log(`  - ${nl.personaId}: "${nl.subject}"`);
  }

  console.log(`\n✓ ${run.campaignIds.length} campaigns sent via mock HubSpot`);
  console.log(`✓ Performance metrics simulated for each segment`);
  console.log(`✓ AI-powered insight report generated`);
  console.log(`\nRun ID: ${run.id}`);
  console.log(`Content package ID: ${contentPackage.id}`);
  console.log(`Insight report ID: ${run.insightReportId}`);
  console.log(`Total duration: ${duration}s\n`);
}

main().catch((err) => {
  console.error("\n❌ Pipeline failed:", err);
  process.exit(1);
});
